### ISSUE TITLE
Seek_Graph doesn't work.

### ISSUE THREAD

**Issue by YeonuiKwak** [CalabreseLab/seekr#6]
Hi, 
I am trying to apply this tool to group genes based on their 3' UTR sequences.
So What I used for seekr_kmer_counts were  21365 sequences of 3'UTRomes.
It seems that seekr_pearson and seekr_kmer_counts worked successfully.
However, when I tried seekr_graph, I got the following messages.

seekr_graph self.npy 0.3 -g example.gml
Traceback (most recent call last):
  File "/anaconda/bin/seekr_graph", line 11, in <module>
    sys.exit(console_graph())
  File "/anaconda/lib/python3.6/site-packages/seekr/console_scripts.py", line 507, in console_graph
    float(args.resolution), int(args.n_comms), args.seed)
  File "/anaconda/lib/python3.6/site-packages/seekr/console_scripts.py", line 482, in _run_graph
    maker.make_gml_csv_files()
  File "/anaconda/lib/python3.6/site-packages/seekr/graph.py", line 177, in make_gml_csv_files
    self.build()
  File "/anaconda/lib/python3.6/site-packages/seekr/graph.py", line 166, in build
    self.graph = networkx.from_numpy_array(self.adj)
AttributeError: module 'networkx' has no attribute 'from_numpy_array'

Do you have any advice on solving this?

Thanks!

**Comment by Jessime** [comment]
Hi!

Do you know what version of networkx is installed? You can try running `pip show networkx` or `conda list networkx` to check.

**Comment by YeonuiKwak** [comment]
Hello,

I updated networkx to a newer version, which seemed to work fine!
By the way, does it usually take that long to run seekr_graph?
For my selfv.s.self.csv file generated from running seekr_pearson, I ran
the command seekr_graph. But it seems to take longer than 1 hour... Should
I stop the cmd or still leave it go until it is over naturally?

Thanks
Yeonui

**Comment by Jessime** [comment]
Glad that fix worked!

An hour is a pretty long time time. A few questions:

1. How many transcripts are you looking at?
2. What is the size of the file output by `seekr_pearson`?
3. What was the exact command you used to run `seekr_graph`?

**Comment by YeonuiKwak** [comment]
1. How many transcripts are you looking at? ~21000 transcripts
   2. What is the size of the file output by seekr_pearson?
   self.vs.self.csv :33.68 GB
   3. What was the exact command you used to run seekr_graph?  seekr_graph
   self.vs.self.csv .3 -g example.gml -c communities.csv  .3 -g example.gml
   -c cD

Do I have to decrease the number of transcripts? How many do you estimate
for the maximum number of transcripts that can be tested with seekr?


Thanks,

Yeonui

**Comment by Jessime** [comment]
21000 transcripts is big, but fine. You probably have too many edges though, and need to adjust your gamma. What size kmer are you using?

**Comment by YeonuiKwak** [comment]
I used 5 mer to create a count k-mer count table.
It took 3 hours to get a gml file after running seekr_graph. As you
suggested, I think I might have to adjust gamma parameter?
By the way, now that I got this gml file, I'd love to visualize the
information in the gml file. However, I am not familiar with how to
visualizes the information in the gml file.
It seems that seekr can generate something like correlation heatmap...
Could you let me know the code to generate plots similar to those in your
paper?

Thanks!!

**Comment by Jessime** [comment]
Yep, I'd suggest raising your gamma parameter. I'm pretty sure the run time of `seeker_graph`, with respect to the number of edges, is `O(n)^2`. If you set gamma properly, you should be able to finish a run in ~5 minutes. It's not part of the README yet, I don't think, by you can try running `seekr_visualize_distro` to get a sense for what different gammas will do to the number of edges in your graph.

Visualizing the gml file can be a little tricky, since we didn't use code to make the images. We used a prograph called Gephi. See if this explanation helps:

>Gephi is open-source software that is useful for visualizing lncRNA community graphs. On launch,
Gephi will provide you with a "Welcome" pop-up window. In the "New Project" section, click "Open
Graph File". Select `v22_sub.gml`. If loaded correctly, you will receive an "Import report" listing
the number of nodes and edges as well as other graph details. Click "OK". In the center of the
main application window, you should see a small black circle. This is the default layout and
coloring of the graph. Next, we'll color and properly layout the nodes. In the top left of the window,
there will be an "Appearance" section. Click "Nodes" -> "Partition" -> "Choose an attribute" ->
"Group" -> "Apply". After a few seconds, the nodes of the graph should be colored by group. On
the bottom left, there is a section called "Layout". Click "Choose a layout" -> "Yifan Hu" -> "Run".
Running the layout will take time. Progress can be tracked in the bottom right. Once finished, savethe image by clicking: "File" -> "Export" -> "SVG/PDF/PNG file" -> "Options". Set "Width" and
"Height" to 4096. Click "OK". Name your file and click "Okay" again. Saving the image will also
some take time.

**Comment by YeonuiKwak** [comment]
Thank you!!!!
Changing gamma really worked to save time.
Also, I could make it to visualizing my gml file using gephi thanks to your
kind instruction.

Best,
Yeonui

**Comment by Jessime** [comment]
Awesome; glad everything worked out! I'm going to close this issue, but feel free to open another if you have more problems/questions.
